### ISSUE TITLE
Works with raspberry?

### ISSUE THREAD

**Issue by VonLisboa** [njmarko/2FAce-verification#3]
What's the low expensive hardware that can run **face-verification-service**?

Works with raspberry?

**Comment by njmarko** [comment]
Face-verification-service can use VGGFace (Resnet50) or FaceNet models, and these models determine the hardware requirements of that service. I can't remember the exact requirements for those models, but there may be some information about them on the internet.

We tested it on two laptops, first with i7 9750h CPU and GTX1660ti graphic card, and second with an old 2-core Intel CPU and no graphic card. Both were able to run the service just fine. 

I don't have a raspberry so I'm not able to test if it works, but the fact that it did work on a 2-core CPU might indicate that raspberry could run it.

**Comment by VonLisboa** [comment]
It really is likely, I will test it, I have a great use case for the Brazilian reality.
thanks!
